### ISSUE TITLE
Can't find the py script

### ISSUE THREAD

**Issue by Bhargav-Rao** [bhavul/miui-forum-search#1]
I ran the command 

    python miuiscraper.py 1 31

But I'm getting an error

    Error: miuiscraper.py not found

**Comment by bhavul** [comment]
Hey, 
Sorry, had not logged into github for a long time. Fixed this repo. Probably forgot uploading the scripts when I made it. Apologies.

**Comment by Bhargav-Rao** [comment]
Nice, Thanks.
